server:
  port: 8080
spring:
  application:
    name: springboot-cache-demo
  # \u914D\u7F6E\u6570\u636E\u5E93\u4FE1\u606F\u548C\u8FDE\u63A5\u6C60
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cache?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      connection-timeout: 20000
  # \u5F00\u542Fjpa \u81EA\u52A8\u5EFA\u8868
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # \u914D\u7F6E\u7F13\u5B58\uFF0C\u521D\u59CB\u5316\u7F13\u5B58\u5BB9\u91CF\uFF0C\u6700\u5927\u5BB9\u91CF\uFF0C\u8FC7\u671F\u65F6\u95F4\uFF08\u8FD9\u91CC\u914D\u7F6E\u5199\u5165\u540E\u8FC7\u671F\u65F6\u95F4\uFF09
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=3s
  # \u914D\u7F6Econtroller\u8DEF\u5F84
swagger:
  base-package: com.sls.web
  title: springboot\u4F7F\u7528caffeine\u7F13\u5B58
